apiVersion: v1
kind: ServiceAccount
metadata:
  name: archaware-controller-serviceaccount
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: archaware-controller-pod-node-editor
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["list", "get", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: archaware-controller-edit-pods-nodes
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: archaware-controller-serviceaccount
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: archaware-controller-pod-node-editor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archaware-controller
  namespace: kube-system
  labels:
    app: archaware-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archaware-controller
  template:
    metadata:
      labels:
        app: archaware-controller
    spec:
      tolerations:
      - key: "supported-arch"
        operator: "Equal"
        value: "arm"
        effect: "NoSchedule"
      - key: "supported-arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"
      serviceAccountName: archaware-controller-serviceaccount
      containers:
      - name: archaware-operator
        image: docker.io/learnitall/archaware-controller:latest
        resources:
          limits:
            cpu: 250m
            memory: 200M
